AWSTemplateFormatVersion: 2010-09-09
Description: OIDC provider that lets GitHub Actions deploy to AWS

Parameters:
    FullRepoName:
        Type: String

Resources:
    Role:
        Type: AWS::IAM::Role
        Properties:
            RoleName: github-actions-ami-publisher
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Action: sts:AssumeRoleWithWebIdentity
                      Principal:
                          Federated: !Ref GithubOidc
                      Condition:
                          StringLike:
                              token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*
            Policies:
                -   PolicyName: AmiPublisherPolicy
                    PolicyDocument:
                        Statement:
                            -   Effect: Allow
                                Action: 'ec2:*'
                                Resource: '*'

    GithubOidc:
        Type: AWS::IAM::OIDCProvider
        Properties:
            Url: https://token.actions.githubusercontent.com
            ThumbprintList: [6938fd4d98bab03faadb97b34396831e3780aea1]
            ClientIdList:
                - sts.amazonaws.com

Outputs:
    Role:
        Value: !GetAtt Role.Arn
